// Code generated by goctl. DO NOT EDIT!
// Source: sum.proto

package sum

import (
	"context"

	"github.com/kevwan/grpc-restful/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Numbers     = pb.Numbers
	SumRequest  = pb.SumRequest
	SumResponse = pb.SumResponse

	Sum interface {
		Add(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	}

	defaultSum struct {
		cli zrpc.Client
	}
)

func NewSum(cli zrpc.Client) Sum {
	return &defaultSum{
		cli: cli,
	}
}

func (m *defaultSum) Add(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	client := pb.NewSumClient(m.cli.Conn())
	return client.Add(ctx, in, opts...)
}
