// Code generated by goctl. DO NOT EDIT!
// Source: sum.proto

package server

import (
	"context"

	"github.com/kevwan/grpc-restful/internal/logic"
	"github.com/kevwan/grpc-restful/internal/svc"
	"github.com/kevwan/grpc-restful/pb"
)

type SumServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSumServer
}

func NewSumServer(svcCtx *svc.ServiceContext) *SumServer {
	return &SumServer{
		svcCtx: svcCtx,
	}
}

func (s *SumServer) Add(ctx context.Context, in *pb.SumRequest) (*pb.SumResponse, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}
